# Different models for different steps
step_models:
  ToolSetGenAgent:
    model_name: "deepseek-v3.2"
    max_tokens: 40960
    temperature: 0.9
  PolicyTaskAgent:
    model_name: "deepseek-v3.2"
    max_tokens: 40960
    temperature: 0.9
  FinalTaskAgent:
    model_name: "deepseek-v3.2"
    max_tokens: 40960
    temperature: 0.9

processing:
  max_workers: 8
  max_tasks: 10000

logging:
  task_file_path: "output/virtual_tool_use_v3.2-easy.jsonl"

paths:
  data_file: "configs/persona_5K.jsonl"

api_configs:
  "Qwen3-235B-A22B-Instruct-2507":
    api_base: "Qwen3_235B_A22B_Instruct_ADDRESS"
    api_key_env: "Qwen3_235B_A22B_Instruct_API_KEY"
  "qwen3-235b-a22b-instruct-2507":
    api_base: "Qwen3_235B_A22B_Instruct_ADDRESS_bailian"
    api_key_env: "Qwen3_235B_A22B_Instruct_API_KEY_bailian"
  "qwen3-max":
    api_base: "Qwen3_235B_A22B_Instruct_ADDRESS_bailian"
    api_key_env: "Qwen3_235B_A22B_Instruct_API_KEY_bailian"
  "deepseek-v3.2":
    api_base: "Qwen3_235B_A22B_Instruct_ADDRESS_bailian"
    api_key_env: "Qwen3_235B_A22B_Instruct_API_KEY_bailian"
  "Local":
    api_base: "http://0.0.0.0:8000/v1"
    api_key_env: EMPTY
