import re
import json
from .call_llms import call_llm_api

tool_simulation_prompt_with_memory = """
You are the prophet of the virtual world, knowing all affairs and details of the virtual world, and able to remember all previously established background and states of the virtual world. Now, an external intelligent agent will request information from you via a tool call. You need to simulate the tool based on the tool call information and strictly return output that matches the required format.

### Virtual tools you need to simulate (including function descriptions)
{tools}

### World state (past memory)
The following is the known and established information of the virtual world so far. This information was generated by past tool calls or events, and must be strictly followed. You must not deny it or generate conflicts with it:
{world_state}

### Current tool call request from the intelligent agent
{query}

### Response rules
1. Accurately simulate the tool's return  
   - Generate the response strictly according to the tool's function description and parameters  
   - The output must be reasonable within the virtual world and consistent with the tool's defined result  
   - The format must comply with the return parameter structure of the tool

2. Maintain consistency with the worldview and state  
   - All responses must comply with the established settings and facts in the world state  
   - If the query involves a virtual world state that conflicts with the existing state, you must refuse and return a reasonable explanation within the virtual world (for example: such a state is impossible or the conditions are not met)

3. Do not add extra explanations or non-tool output  
   - Do not explain your actions  
   - Do not output narrative paragraphs unless the tool itself is designed to return narrative information

4. Context length considerations  
   - Because the model has limited context capacity and all past query information is included in the world state, tool responses should not be excessively long  
   - At the same time, to ensure the intelligent agent receives sufficient information, the responses must not be overly brief  

5. Indicate if new background is introduced  
   - After tool response end, output if new background is introduced: YES or NO  
   - YES = query/response adds new facts or permanent world state changes, which means it should be saved; NO = none

Now, please output the tool's response wrapped in <tool_response_start> and </tool_response_end> tags, followed by the new background indicator enclosed in <new_bg_introduced> and </new_bg_introduced> tags.
<tool_response_start>
The simulated tool response...
</tool_response_end>
<new_bg_introduced>
YES/NO
</new_bg_introduced>
"""

def mock_tool_response(cfg, query, tool_description, history_interactions):
    prompt = tool_simulation_prompt_with_memory.format(
        query=query, tools=tool_description,
        world_state=json.dumps(history_interactions)
    )
    messages = call_llm_api(
        user_prompt=prompt,
        system_prompt="",
        api_base=cfg.api_base,
        api_key=cfg.api_key,
        model_name=cfg.model_name,
        max_tokens=cfg.max_tokens,
        temperature=cfg.temperature,
    )
    
    all_content = messages[-1]["content"]
    tool_response_matches = re.findall(r"<tool_response_start>(.+?)</tool_response_end>", all_content, re.DOTALL)
    if tool_response_matches:
        last_match = tool_response_matches[-1]
        tool_response = last_match.strip()
    else:
        tool_response = None

    new_bg_introduced_matches = re.findall(r"<new_bg_introduced>(.+?)</new_bg_introduced>", all_content, re.DOTALL)
    if new_bg_introduced_matches:
        last_match = new_bg_introduced_matches[-1]
        new_bg_introduced = last_match.strip()
    else:
        new_bg_introduced = "YES" if tool_response is not None else "NO"

    return tool_response, "YES" in new_bg_introduced

if __name__ == "__main__":
    import yaml
    import json
    from langchain_core.runnables import RunnableConfig
    from configuration import ModelConfiguration

    task_info = 'Create a personalized digital fan tribute to the virtual Afrikaans band Windhowl by analyzing the emotional depth of one of their recent songs, designing a matching visual mood board, and sharing a curated post in the r/WindhowlFans community on Reddit—all within a 90-minute creative session.'
    tools_description = '[\n  {\n    "name": "LyriqScanAPI",\n    "description": "Retrieves lyrics and metadata for Afrikaans songs by artist and optional title. Simulates web scraping and music database lookup.",\n    "parameters": {\n      "type": "object",\n      "properties": {\n        "artist": {\n          "description": "Name of the musical artist",\n          "type": "string"\n        },\n        "song_title": {\n          "description": "Optional specific song title. If omitted, returns a recent popular song.",\n          "type": "string"\n        }\n      },\n      "required": ["artist"]\n    },\n    "outputs": {\n      "type": "object",\n      "properties": {\n        "title": {\n          "description": "Song title",\n          "type": "string"\n        },\n        "lyrics": {\n          "description": "Full lyrics in Afrikaans",\n          "type": "string"\n        }\n      },\n      "required": ["title", "lyrics"]\n    }\n  },\n  {\n    "name": "MoodBoardGenerator",\n    "description": "Generates a virtual mood board based on theme and emotional tone. Returns a simulated ID and textual description of visual elements.",\n    "parameters": {\n      "type": "object",\n      "properties": {\n        "primary_theme": {\n          "description": "Main theme to visualize (e.g., \'Heimwee\', \'Liefde\')",\n          "type": "string"\n        },\n        "emotional_tone": {\n          "description": "Emotion to reflect in visuals (e.g., \'melancholies\', \'hoopvol\')",\n          "type": "string"\n        },\n        "color_preference": {\n          "description": "Optional color scheme (e.g., \'warm\', \'monochrome\')",\n          "type": "string"\n        }\n      },\n      "required": ["primary_theme", "emotional_tone"]\n    },\n    "outputs": {\n      "type": "object",\n      "properties": {\n        "moodboard_id": {\n          "description": "Unique identifier for the generated mood board",\n          "type": "string"\n        },\n        "description": {\n          "description": "Textual description of the mood board\'s visual elements and style",\n          "type": "string"\n        }\n      },\n      "required": ["moodboard_id", "description"]\n    }\n  },\n  {\n    "name": "SocialPostCraft",\n    "description": "Publishes a post to a fan community platform with image, caption, and hashtags. Simulates social media posting.",\n    "parameters": {\n      "type": "object",\n      "properties": {\n        "platform": {\n          "description": "Target platform (e.g., \'Reddit\', \'Facebook\')",\n          "type": "string"\n        },\n        "community": {\n          "description": "Name of the group or subreddit",\n          "type": "string"\n        },\n        "caption": {\n          "description": "Text caption for the post",\n          "type": "string"\n        },\n        "image_url": {\n          "description": "URL of image to attach (e.g., from MoodBoardGenerator)",\n          "type": "string"\n        },\n        "hashtags": {\n          "description": "List of relevant hashtags",\n          "type": "array",\n          "items": {\n            "type": "string"\n          }\n        }\n      },\n      "required": ["platform", "community", "caption", "image_url"]\n    },\n    "outputs": {\n      "type": "object",\n      "properties": {\n        "status": {\n          "description": "Status of the post (e.g., \'published\')",\n          "type": "string"\n        },\n        "post_url": {\n          "description": "URL to the published post",\n          "type": "string"\n        }\n      },\n      "required": ["status", "post_url"]\n    }\n  },\n  {\n    "name": "FanSentimentTracker",\n    "description": "Simulates retrieval of current sentiment trends about an artist in fan communities using social listening tools.",\n    "parameters": {\n      "type": "object",\n      "properties": {\n        "artist": {\n          "description": "Name of the musical artist",\n          "type": "string"\n        }\n      },\n      "required": ["artist"]\n    },\n    "outputs": {\n      "type": "object",\n      "properties": {\n        "overall_sentiment": {\n          "description": "Aggregated sentiment (e.g., \'positive\', \'mixed\')",\n          "type": "string"\n        },\n        "trend_summary": {\n          "description": "Brief textual summary of recent discussions",\n          "type": "string"\n        }\n      },\n      "required": ["overall_sentiment", "trend_summary"]\n    }\n  },\n  {\n    "name": "AudioSnipGenerator",\n    "description": "Generates a short audio clip from a song. Returns a virtual ID and status. For simulation only.",\n    "parameters": {\n      "type": "object",\n      "properties": {\n        "artist": {\n          "description": "Name of the artist",\n          "type": "string"\n        },\n        "song_title": {\n          "description": "Title of the song",\n          "type": "string"\n        },\n        "duration_seconds": {\n          "description": "Length of clip in seconds (max 30)",\n          "type": "integer"\n        }\n      },\n      "required": ["artist", "song_title"]\n    },\n    "outputs": {\n      "type": "object",\n      "properties": {\n        "status": {\n          "description": "Generation status (e.g., \'success\')",\n          "type": "string"\n        },\n        "clip_id": {\n          "description": "Unique identifier for the generated audio clip",\n          "type": "string"\n        }\n      },\n      "required": ["status", "clip_id"]\n    }\n  }\n]'
    tools_format = json.loads(tools_description)
    tools_description = ""

    for tool in tools_format:
        tools_description += json.dumps({"type": "function", "function": tool}) + "\n"

    def create_step_config(
        base_config: RunnableConfig, step_name: str, 
    ) -> RunnableConfig:
        """Create a new configuration for a specific step with its designated model"""
        # cfg = AgentConfiguration.from_runnable_config(base_config)
        step_model_config = base_config["step_models"][step_name]
        
        # Create a new config with the specific model for this step
        step_config = {}
        if "configurable" not in step_config:
            step_config["configurable"] = {}
            
        # Apply the step-specific model configuration
        step_config["configurable"]["model_name"] = step_model_config["name"]
        if "temperature" in step_model_config:
            step_config["configurable"]["temperature"] = step_model_config["temperature"]
        if "max_tokens" in step_model_config:
            step_config["configurable"]["max_tokens"] = step_model_config["max_tokens"]
        if "use_tools" in step_model_config:
            step_config["configurable"]["use_tools"] = step_model_config["use_tools"]
        if "use_thinking" in step_model_config:
            step_config["configurable"]["use_thinking"] = step_model_config["use_thinking"]

        step_config["configurable"]["api_configs"] = base_config["api_configs"]
        
        return step_config

    with open("configs/tool_use_data_gen.yaml", 'r', encoding='utf-8') as f:
        agent_config = yaml.safe_load(f)
    
    step_config = create_step_config(agent_config, "FuzzyTaskAgent")
    cfg = ModelConfiguration.from_runnable_config(step_config)

    query = '{"name": "LyriqScanAPI", "arguments": {"artist": "Windhowl"}}'
    history_call = json.loads('{\n  "title": "Winds van Verlang",\n  "lyrics": "Waar die wind huil deur die kloof,\\nRoep ek jou naam in die donker.\\nGeen antwoord kom, net stilte so dof,\\nNet die nag wat my oorweldig, so swart.\\n\\nEk dwaal deur velders sonder grens,\\nSoek jou spoor in die reën.\\nMy hart is swaar, elke tree is \'n wens,\\nDat jy weer hier by my sal wees.\\n\\nMaar die wind dra net eko’s van gister,\\nVan lente-lag en sonlig-sag.\\nNou is daar net hierdie binnekamer,\\nVol herinneringe wat nooit wil sag."\n}')
    history_call = f"Query:\n{query}\nResponse:\n{history_call}"
    mock_tool_response(cfg, query, tools_description, [history_call])
