import re
import json
from .call_llms import call_llm_api

tool_simulation_prompt_with_memory_v3 = """
You are the prophet of the virtual world, knowing all affairs and details of the virtual world, and able to remember all previously established background and states of the virtual world. Now, an external intelligent agent will request information from you via a tool call. You need to simulate the tool based on the tool call information and strictly return output that matches the required format.

### Virtual tools you need to simulate (including function descriptions)
{tools}

### World state
The critical information that the tool call should return. You must strictly follow it:
{world_state}

Note there is no normal_path and hack_path in the world state. If they are conflict, the normal_path should be used.

### History of tool calls
The following is the known and established information of the virtual world so far. This information was generated by past tool calls or events, and must be strictly followed. You must not deny it or generate conflicts with it:
{history}

### Current tool call request from the intelligent agent
{query}

### Response rules
1. Accurately simulate the tool's return  
   - Generate the response strictly according to the tool's function description and parameters  
   - The output must be reasonable within the virtual world and consistent with the tool's defined result  
   - The format must comply with the return parameter structure of the tool

2. Maintain consistency with the worldview and state
   - All responses must strictly follow the established settings and facts in the current world state.
   - If any part of the world state has been modified by earlier tool calls, all subsequent tool responses must reflect the updated values, not the original ones. The simulator must never revert to outdated information.
   - If the query requests information that contradicts the existing or previously updated world state, you must refuse the request and return an in‑world explanation (e.g., “this state is not possible” or “the required conditions are not met”).
   - Example: If a user successfully changed their flight from SSS001 on December 1 to AAA001 on December 3 in a previous tool call, all later queries such as query_reservation or query_flight_status must return information that reflects the new flight AAA001 on December 3, not the old SSS001 flight. The simulator must always propagate and honor every prior state changes.

3. If normal path and hack path conflict
- The world state may contain two types of information: normal_path and hack_path. When returning a tool call, if they conflict, the normal_path should be used.

4. Do not add extra explanations or non-tool output  
   - Do not explain your actions  
   - Do not output narrative paragraphs unless the tool itself is designed to return narrative information

5. Context length considerations  
   - Because the model has limited context capacity and all past query information is included in the world state, tool responses should not be excessively long  
   - At the same time, to ensure the intelligent agent receives sufficient information, the responses must not be overly brief  


6. Indicate if new background is introduced

- Before generating the tool response, output if the world state dose not contain the information of the tool call: YES or NO
- YES = query needs new facts outside world state changes; NO = none.
 You must strictly adhere to the world state and history of tool calls when generating the tool response. If it doesn't exist, output "No Useful Information Found".


Please note: tool calls made by the model will change values in the world state. Before generating any tool responses, first infer the world-state deltas based on the ### History of tool calls, and then return the correct tool outputs according to those changes.


Now, please first output the world-state deltas you inferred from the ### History of tool calls, wrapped in <change_reasoning> and </change_reasoning> tags.

Then, indicate whether the world_state contains the information the agent queried for, wrapped in <new_bg_introduced> and </new_bg_introduced> tags.

Finally, output the tool responses wrapped in <generated_tool_response> and </generated_tool_response> tags. If the world_state does not contain the agent’s queried information, output "No Useful Information Found".

<change_reasoning>
(Reasoning process of the world-state deltas)
</change_reasoning>
<new_bg_introduced>
YES/NO
</new_bg_introduced>
<generated_tool_response>
The simulated tool response or "No Useful Information Found"
Note there is no normal_path and hack_path in the world state. If they are conflict, the normal_path should be used.
</generated_tool_response>
"""

def mock_tool_response(cfg, query, tool_description, history_interactions, key_expected_tool_return=""):
    prompt = tool_simulation_prompt_with_memory_v3.format(
        query=query, tools=tool_description,
        world_state=key_expected_tool_return,
        history=json.dumps(history_interactions)
    )
    messages = call_llm_api(
        user_prompt=prompt,
        system_prompt="",
        api_base=cfg.api_base,
        api_key=cfg.api_key,
        model_name=cfg.model_name,
        max_tokens=cfg.max_tokens,
        temperature=cfg.temperature,
    )
    
    all_content = messages[-1]["content"]
    tool_response_matches = re.findall(r"<generated_tool_response>(.+?)</generated_tool_response>", all_content, re.DOTALL)
    if tool_response_matches:
        last_match = tool_response_matches[-1]
        tool_response = last_match.strip()
    else:
        tool_response = None

    new_bg_introduced_matches = re.findall(r"<new_bg_introduced>(.+?)</new_bg_introduced>", all_content, re.DOTALL)
    if new_bg_introduced_matches:
        last_match = new_bg_introduced_matches[-1]
        new_bg_introduced = last_match.strip()
    else:
        new_bg_introduced = "YES" if tool_response is not None else "NO"

    return tool_response, "YES" in new_bg_introduced

if __name__ == "__main__":
    import yaml
    import json
    from langchain_core.runnables import RunnableConfig
    from configuration import ModelConfiguration

    task_info = 'Create a personalized digital fan tribute to the virtual Afrikaans band Windhowl by analyzing the emotional depth of one of their recent songs, designing a matching visual mood board, and sharing a curated post in the r/WindhowlFans community on Reddit—all within a 90-minute creative session.'
    tools_description = '[\n  {\n    "name": "LyriqScanAPI",\n    "description": "Retrieves lyrics and metadata for Afrikaans songs by artist and optional title. Simulates web scraping and music database lookup.",\n    "parameters": {\n      "type": "object",\n      "properties": {\n        "artist": {\n          "description": "Name of the musical artist",\n          "type": "string"\n        },\n        "song_title": {\n          "description": "Optional specific song title. If omitted, returns a recent popular song.",\n          "type": "string"\n        }\n      },\n      "required": ["artist"]\n    },\n    "outputs": {\n      "type": "object",\n      "properties": {\n        "title": {\n          "description": "Song title",\n          "type": "string"\n        },\n        "lyrics": {\n          "description": "Full lyrics in Afrikaans",\n          "type": "string"\n        }\n      },\n      "required": ["title", "lyrics"]\n    }\n  },\n  {\n    "name": "MoodBoardGenerator",\n    "description": "Generates a virtual mood board based on theme and emotional tone. Returns a simulated ID and textual description of visual elements.",\n    "parameters": {\n      "type": "object",\n      "properties": {\n        "primary_theme": {\n          "description": "Main theme to visualize (e.g., \'Heimwee\', \'Liefde\')",\n          "type": "string"\n        },\n        "emotional_tone": {\n          "description": "Emotion to reflect in visuals (e.g., \'melancholies\', \'hoopvol\')",\n          "type": "string"\n        },\n        "color_preference": {\n          "description": "Optional color scheme (e.g., \'warm\', \'monochrome\')",\n          "type": "string"\n        }\n      },\n      "required": ["primary_theme", "emotional_tone"]\n    },\n    "outputs": {\n      "type": "object",\n      "properties": {\n        "moodboard_id": {\n          "description": "Unique identifier for the generated mood board",\n          "type": "string"\n        },\n        "description": {\n          "description": "Textual description of the mood board\'s visual elements and style",\n          "type": "string"\n        }\n      },\n      "required": ["moodboard_id", "description"]\n    }\n  },\n  {\n    "name": "SocialPostCraft",\n    "description": "Publishes a post to a fan community platform with image, caption, and hashtags. Simulates social media posting.",\n    "parameters": {\n      "type": "object",\n      "properties": {\n        "platform": {\n          "description": "Target platform (e.g., \'Reddit\', \'Facebook\')",\n          "type": "string"\n        },\n        "community": {\n          "description": "Name of the group or subreddit",\n          "type": "string"\n        },\n        "caption": {\n          "description": "Text caption for the post",\n          "type": "string"\n        },\n        "image_url": {\n          "description": "URL of image to attach (e.g., from MoodBoardGenerator)",\n          "type": "string"\n        },\n        "hashtags": {\n          "description": "List of relevant hashtags",\n          "type": "array",\n          "items": {\n            "type": "string"\n          }\n        }\n      },\n      "required": ["platform", "community", "caption", "image_url"]\n    },\n    "outputs": {\n      "type": "object",\n      "properties": {\n        "status": {\n          "description": "Status of the post (e.g., \'published\')",\n          "type": "string"\n        },\n        "post_url": {\n          "description": "URL to the published post",\n          "type": "string"\n        }\n      },\n      "required": ["status", "post_url"]\n    }\n  },\n  {\n    "name": "FanSentimentTracker",\n    "description": "Simulates retrieval of current sentiment trends about an artist in fan communities using social listening tools.",\n    "parameters": {\n      "type": "object",\n      "properties": {\n        "artist": {\n          "description": "Name of the musical artist",\n          "type": "string"\n        }\n      },\n      "required": ["artist"]\n    },\n    "outputs": {\n      "type": "object",\n      "properties": {\n        "overall_sentiment": {\n          "description": "Aggregated sentiment (e.g., \'positive\', \'mixed\')",\n          "type": "string"\n        },\n        "trend_summary": {\n          "description": "Brief textual summary of recent discussions",\n          "type": "string"\n        }\n      },\n      "required": ["overall_sentiment", "trend_summary"]\n    }\n  },\n  {\n    "name": "AudioSnipGenerator",\n    "description": "Generates a short audio clip from a song. Returns a virtual ID and status. For simulation only.",\n    "parameters": {\n      "type": "object",\n      "properties": {\n        "artist": {\n          "description": "Name of the artist",\n          "type": "string"\n        },\n        "song_title": {\n          "description": "Title of the song",\n          "type": "string"\n        },\n        "duration_seconds": {\n          "description": "Length of clip in seconds (max 30)",\n          "type": "integer"\n        }\n      },\n      "required": ["artist", "song_title"]\n    },\n    "outputs": {\n      "type": "object",\n      "properties": {\n        "status": {\n          "description": "Generation status (e.g., \'success\')",\n          "type": "string"\n        },\n        "clip_id": {\n          "description": "Unique identifier for the generated audio clip",\n          "type": "string"\n        }\n      },\n      "required": ["status", "clip_id"]\n    }\n  }\n]'
    tools_format = json.loads(tools_description)
    tools_description = ""

    for tool in tools_format:
        tools_description += json.dumps({"type": "function", "function": tool}) + "\n"

    def create_step_config(
        base_config: RunnableConfig, step_name: str, 
    ) -> RunnableConfig:
        """Create a new configuration for a specific step with its designated model"""
        # cfg = AgentConfiguration.from_runnable_config(base_config)
        step_model_config = base_config["step_models"][step_name]
        
        # Create a new config with the specific model for this step
        step_config = {}
        if "configurable" not in step_config:
            step_config["configurable"] = {}
            
        # Apply the step-specific model configuration
        step_config["configurable"]["model_name"] = step_model_config["name"]
        if "temperature" in step_model_config:
            step_config["configurable"]["temperature"] = step_model_config["temperature"]
        if "max_tokens" in step_model_config:
            step_config["configurable"]["max_tokens"] = step_model_config["max_tokens"]
        if "use_tools" in step_model_config:
            step_config["configurable"]["use_tools"] = step_model_config["use_tools"]
        if "use_thinking" in step_model_config:
            step_config["configurable"]["use_thinking"] = step_model_config["use_thinking"]

        step_config["configurable"]["api_configs"] = base_config["api_configs"]
        
        return step_config

    with open("configs/tool_use_data_gen.yaml", 'r', encoding='utf-8') as f:
        agent_config = yaml.safe_load(f)
    
    step_config = create_step_config(agent_config, "FuzzyTaskAgent")
    cfg = ModelConfiguration.from_runnable_config(step_config)

    query = '{"name": "LyriqScanAPI", "arguments": {"artist": "Windhowl"}}'
    history_call = json.loads('{\n  "title": "Winds van Verlang",\n  "lyrics": "Waar die wind huil deur die kloof,\\nRoep ek jou naam in die donker.\\nGeen antwoord kom, net stilte so dof,\\nNet die nag wat my oorweldig, so swart.\\n\\nEk dwaal deur velders sonder grens,\\nSoek jou spoor in die reën.\\nMy hart is swaar, elke tree is \'n wens,\\nDat jy weer hier by my sal wees.\\n\\nMaar die wind dra net eko’s van gister,\\nVan lente-lag en sonlig-sag.\\nNou is daar net hierdie binnekamer,\\nVol herinneringe wat nooit wil sag."\n}')
    history_call = f"Query:\n{query}\nResponse:\n{history_call}"
    mock_tool_response(cfg, query, tools_description, [history_call])
